Dark Mode
Idrinth/api-bench pull request #162
Opened 2024-01-18 15:10 UTC by MohamedSy1

I was able to add dark mode for the website

2024-01-19 04:07 UTC, Idrinth requested changes

2024-01-19 04:07 UTC, Idrinth commented on website/src/index.css
> +  --white: #fff;
please return this to hsla :)

2024-01-19 04:07 UTC, Idrinth commented on website/src/index.css
> +  --black: hsla(0deg 0% 0% / 100%);
please remove the added whitespace

2024-01-19 04:07 UTC, Idrinth commented on website/src/index.css
> +      text-decoration: underline;
not a colot, please remove

2024-01-19 04:07 UTC, Idrinth commented on website/src/index.css
> +      text-decoration: none;
not a color, please remove

2024-01-19 04:07 UTC, Idrinth commented on website/src/index.css
> +      color: var(#fff);
don't those belong in the body?

2024-01-23 15:00 UTC, MohamedSy1 commented
Done

2024-01-23 16:21 UTC, Idrinth requested changes

2024-01-23 16:21 UTC, Idrinth commented on website/src/index.css
> +      font-size: 130%;
not a color, please remove

2024-01-23 16:21 UTC, Idrinth commented on website/src/index.css
> +      background-color: #090807;
why are those in root? Shouldn't they be in html or body?

2024-01-23 16:21 UTC, Idrinth commented on website/src/index.css
> +  --white: hsla(0deg 0% 95% / 100%);
why the change by 5%?

2024-01-25 02:24 UTC, Idrinth commented
I think we need to go through this together. The merge broke a lot of the css by deleting large parts of it, then there are generated files being added and lastly a new package being added to the website package.json.

Let me know when you're available.

2024-01-26 06:47 UTC, Idrinth approved these changes

2024-01-26 06:47 UTC, merged