fix(documentation-website): remove unnecessary media query
Idrinth/api-bench pull request #631
Opened 2024-04-02 18:18 UTC by itsmacr8

# The Pull Request is ready

- [x] fixes #608 
- [ ] all actions are passing
- [x] only fixes a single issue

## Overview

remove unnecessary media query that were add for mobile devices. It is not needed because it is a mobile first design

## Review points

## Documentation-Website

- [x] mobile view is usable
- [x] desktop view is usable
- [ ] no a-tags are used directly (NavLink, MailLink, ExternalLink instead)
- [ ] all new texts are added to the translation files (at least the english one)
- [ ] tests have been added (if required)
- [ ] shared code has been extracted in a different file

## Notes

2024-04-02 19:17 UTC, Idrinth requested changes

2024-04-02 19:17 UTC, Idrinth commented on documentation-website/src/index.css
> +footer {
the idea was to keep the functionality, this will likely break it.

2024-04-04 06:42 UTC, Idrinth commented
@coderabbitai review

2024-04-04 18:12 UTC, itsmacr8 commented
@Idrinth All checks passed. Is it okay to merge?

2024-04-04 18:41 UTC, Idrinth commented
> @Idrinth All checks passed. Is it okay to merge?

yes, perfect!

2024-04-04 18:41 UTC, merged