Reddit social link
Idrinth/api-bench pull request #666
Opened 2024-04-04 19:32 UTC by KirilCycle

# The Pull Request is ready

- [ ] fixes #639 
- [ ] all actions are passing
- [ ] only fixes a single issue

## Documentation-Website

- [ ] mobile view is usable
- [ ] desktop view is usable
- [ ] no a-tags are used directly (NavLink, MailLink, ExternalLink instead)
- [ ] all new texts are added to the translation files (at least the english one)
- [ ] tests have been added (if required)
- [ ] shared code has been extracted in a different file

## Notes

2024-04-04 19:36 UTC, KirilCycle commented
Upps, accidentaly added extra commit

2024-04-05 05:08 UTC, Idrinth requested changes

2024-04-05 05:08 UTC, Idrinth commented on documentation-website/language/en.yml
> +    title: "@idrinth/api-bench on reddit"
shouldn't reddit be Reddit?

2024-04-05 11:33 UTC, KirilCycle commented on documentation-website/language/en.yml
> +    title: "@idrinth/api-bench on reddit"
This is TabNine fault)

2024-04-05 14:06 UTC, merged