docs(documentation-website):Add npm run local to Contributor Guidelines
Idrinth/api-bench pull request #737
Opened 2024-04-08 11:59 UTC by akhil0203

# The Pull Request is ready

- [x] fixes #736 
- [x] all actions are passing
- [x] only fixes a single issue

## Overview

This pull request addresses the issue by updating the contributor guidelines to include instructions for running Continuous Integration (CI) tasks locally using the npm run local command. 

## Documentation-Website

- [ ] mobile view is usable
- [ ] desktop view is usable
- [x] no a-tags are used directly (NavLink, MailLink, ExternalLink instead)
- [ ] all new texts are added to the translation files (at least the english one)
- [ ] tests have been added (if required)
- [ ] shared code has been extracted in a different file

2024-04-08 12:46 UTC, Idrinth commented
@akhil0203 thank you for helping! Do you want to add the website changes as well? If not I'll merge the doc changes.

Files:
/documentation-website/language/en.yml
/documentation-website/src/pages/contributing/index.tsx

2024-04-08 13:09 UTC, Idrinth requested changes

2024-04-08 13:09 UTC, Idrinth commented on CONTRIBUTING.md
> +To see a list of available CI tasks and their corresponding commands to run them locally, you can run `npm run local` in the source folder. This is particularly useful for testing specific CI tasks b
we usually add a line break after 80 characters to make it unnecessary to scroll

2024-04-08 13:09 UTC, Idrinth commented on CONTRIBUTING.md
> +npm run local
I doubt anyone would clone the repo just to get a list of tests, please remove the code here

2024-04-08 13:54 UTC, akhil0203 commented
> @akhil0203 thank you for helping! Do you want to add the website changes as well? If not I'll merge the doc changes.
> 
> Files: /documentation-website/language/en.yml /documentation-website/src/pages/contributing/index.tsx

i would love to do it ,as this is my first contribution to this awesome project i may take some time to sort it out but i will complete the task

2024-04-08 14:14 UTC, Idrinth commented
> > @akhil0203 thank you for helping! Do you want to add the website changes as well? If not I'll merge the doc changes.
> > Files: /documentation-website/language/en.yml /documentation-website/src/pages/contributing/index.tsx
> 
> i would love to do it ,as this is my first contribution to this awesome project i may take some time to sort it out but i will complete the task

thanks, if you need any help, just ask - you can find at least me on our slack :) There is a guide to the language files on our youtube, that may actually help a bit: https://www.youtube.com/watch?v=FEYIeMCrrbk

2024-04-10 14:17 UTC, Idrinth commented
@akhil0203 will merge the current change already, so we have you among the contributors already :) not taking the task away from you, just create a fresh branch for it please!

2024-04-10 14:18 UTC, merged