Issue website add lighthouse check
Idrinth/api-bench pull request #793
Opened 2024-04-12 11:30 UTC by owais34

# The Pull Request is ready

- [ ] fixes #740 
- [ ] all actions are passing
- [ ] only fixes a single issue

## Overview

Added script to include lighthouse check , comparing high level points for current website and live website.

## Review points

## Documentation-Website

- [ ] mobile view is usable
- [ ] desktop view is usable
- [ ] no a-tags are used directly (NavLink, MailLink, ExternalLink instead)
- [ ] all new texts are added to the translation files (at least the english one)
- [ ] tests have been added (if required)
- [ ] shared code has been extracted in a different file

## Notes

2024-04-12 15:17 UTC, Idrinth requested changes

2024-04-12 15:17 UTC, Idrinth commented on documentation-website/tools/lighthouse-report.js
> +process.exit(0,);
we should have a constants file with them already, if not please create one!

2024-04-12 17:36 UTC, owais34 commented
@Idrinth  , got it I'll resolve above issues 👍

2024-04-13 06:44 UTC, owais34 commented
@Idrinth  , there seems to be some issue with the server run scripts.
Ive tried : 
1. npm start
2. npm serve
The server is hosted , but upon visiting the url a blank page is displayed. The dist/index.html page doesn't have any script tags.
Only npm run dev , seems to host the website locally.

2024-04-13 11:02 UTC, Idrinth commented
> @Idrinth , there seems to be some issue with the server run scripts. Ive tried :
> 
>     1. npm start
> 
>     2. npm serve
> 
> 
> The server is hosted , but upon visiting the url a blank page is displayed. The dist/index.html page doesn't have any script tags. Only npm run dev , seems to host the website locally.

On linux(the actions run on linux) that works :( odd, will try to figure out what goes wrong there

2024-04-13 15:41 UTC, Idrinth approved these changes

2024-04-13 17:20 UTC, merged

2024-04-13 17:20 UTC, Idrinth commented
thanks a lot @owais34 :)

2024-04-13 17:24 UTC, owais34 commented
@Idrinth , you're welcome sir ;).