refactor(framework):clean up function analyzer #780
Idrinth/api-bench pull request #852
Opened 2024-04-21 09:59 UTC by akhil0203

# The Pull Request is ready

- [x] fixes #780 
- [x] all actions are passing

## Overview

RegExp.exec() method is used instead of string.match() as suggested in sonar cloud analysis
multiple module-global constants are created for repeated RegExp.

## Review points

creation of multiple module-global constants

## Framework

- [x] default behaviour did not change

2024-04-21 20:26 UTC, Idrinth commented
@akhil0203  please restore the eslint ignores properly, then everything should pass again, otherwise good work!

2024-04-21 20:27 UTC, Idrinth requested changes
- rename regexp for what the do, not where they are used
- restore eslint-disable-next-line to make eslint pass

2024-04-27 14:42 UTC, Idrinth commented
Hi @akhil0203 ,
This looks good, just can't be merged right now due to conflicts. Please merge the-one into this.

2024-04-28 21:29 UTC, Idrinth commented on framework/src/helper/function-analyzer.ts
> +const commentBlockOrWhitespaceRegExp=/^.*\/\*|\*\/.+$/gu;
@coderabbitai unicode matching is required by default in this project.

2024-04-29 08:01 UTC, akhil0203 commented
> * rename regexp for what the do, not where they are used
> * restore eslint-disable-next-line to make eslint pass



> Hi @akhil0203 , This looks good, just can't be merged right now due to conflicts. Please merge the-one into this.

hi @Idrinth its done please review it.Thanks

2024-04-30 17:30 UTC, merged