Issue curl call to route
Idrinth/api-bench pull request #855
Opened 2024-04-21 19:06 UTC by owais34

# The Pull Request is ready

- [ ] fixes #813 
- [ ] all actions are passing
- [ ] only fixes a single issue

## Overview

Added a cli binary tool to convert a generic curl call to a route file.

## Review points

Convert the already working code , to a cleaner design pattern.

## CLI

- [ ] the change works with both supported node versions
- [ ] the default behaviour did not change
- [ ] shared code has been extracted in a different file

## Notes

2024-04-21 20:38 UTC, Idrinth requested changes
Looks pretty good already!

2024-04-21 20:38 UTC, Idrinth commented on cli/bin/generate-benchmark-from-curl.js
> +import create from '../src/cli/har-route-builder.js';
wrong file

2024-04-21 20:38 UTC, Idrinth commented on cli/package.json
> +    "generate-benchmark-from-curl": "bin/generate-benchmark-from-curl.js",
please also add a short form below, following the usual rules

2024-04-21 20:38 UTC, Idrinth commented on cli/src/cli/curl-route-builder.ts
> +      // eslint-disable-next-line max-len, no-magic-numbers
Why not use a constant here?

2024-04-21 20:38 UTC, Idrinth commented on cli/src/cli/curl-route-builder.ts
> +  routeParams.url = args[args.length-1];
Why not use a constant here?

2024-04-21 20:38 UTC, Idrinth commented on cli/src/cli/curl-route-builder.ts
> +const request: Request = new Request('${ routeParams.url }', requestInit,);
Request is not imported from anywhere - why not make this a simple object?

2024-04-22 04:36 UTC, owais34 commented
@Idrinth , i'll fix the above issues  👍

2024-04-23 15:59 UTC, Idrinth submitted a review, later dismissed

2024-04-23 16:02 UTC, merged